"""Se agregar columna passwd_hash

Revision ID: 9e8f5bcc358e
Revises: 2986d3f3ad53
Create Date: 2025-06-05 20:02:29.929949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8f5bcc358e'
down_revision = '2986d3f3ad53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
